### ISSUE TITLE
White square overlay in the way of selecting a db under the connect dialog

### ISSUE THREAD

**Issue by ExMateria** [shaunxcode/datomicism#1]
I'm a complete noob so apologies in advance for whatever noobness you have to endure.

First off this is AWESOME. Finding it made my day. I'm working on a datomic based clojure app and the last year or so I've been going from knowing nothing about Linux or Clojure to finally getting a VM set up where I can start to implement a schema from a project I started over 5 years ago when I picked up a SQL Server 2005 for Dummies book.

You have one of the best things since sliced bread IMO.

To the issue now.

I'm using Debian and have had a remarkably easy (The first six months trying to figure out  Linux/Debian were hellish at moments for me) time installing nodejs and then datomicism. It took me a bit of time to figure out what I was doing wrong but I got datomicism running and datomic's REST going. Created a little hello mem database thingy and then when I opened my Opera browser (I've only got Opera and Epiphany browsers at present on my Debian VM---please advise me if you know of more desirable browsers to be using) and the problem I have with Opera is that I tab to host and port in the connect dialog (because they are hidden behind a white translucent square that covers the text boxes and the close button) and then when the db: selection dropdown comes up I can't access it to choose a db.

Honestly if just installing another browser was the best way to presently deal with this then I'm cool with that. If I can get just the functionality I saw in your video I'll be a content little noob.

Thanks again for putting such a wonderful thing together!

**Comment by shaunxcode** [comment]
Hey quick answer (that I should note in readme) is that this is only designed to work in chrome right now. I am also working on a packaged version which requires no node js installation. But full cross browser support is definitely a concern and as such I will leave this open.

**Comment by shaunxcode** [comment]
This was resolved by refactoring the way the connection dialog and explorer interact (e.g. fixed the z-index)
