### ISSUE TITLE
Thank you for building this. I am finding it very useful. + Suggestion

### ISSUE THREAD

**Issue by devn** [shaunxcode/datomicism#5]
Thank you for building this!

A couple of suggestions:
- Could you make it more obvious that you need to drag and drop from the top bar? Some sort of highlight or something? I jumped in without fully reading the README and was initially confused because Browser seems to pop up when you click it, but the other buttons require you drag in order to put them in the namespace.
- I don't believe "localhost" works in the hostname field for connecting. In your documentation it clearly says "valid IP", but perhaps some kind of visual validation would be nice.
- I have a feeling that if you included screenshots in the README you'd attract a larger number of users.

All of the above is just marketing and usability. As far as I'm concerned this tool is wonderful as it is, I'm just looking for a reason to keep you developing it because I think it's a great way to understand and build complex schemas.

Thanks!

**Comment by devn** [comment]
One additional suggestion would be to have tooltips that include the documentation you provide in the README when you hover over various widget types.

**Comment by shaunxcode** [comment]
Thank you for the feedback, I am currently working on a new version which
should address many of these usability issues. Please let me know any other
areas you find confusing/unintuitive. I am stoked you are getting utility
out of it regardless!

**Comment by shaunxcode** [comment]
Hey, I am closing this now that I have added an icon the widgets tool bar items to make them "apparent" that they are draggable as well as the tooltips you suggested. I am working on embedding images/videos in the readme.
