### ISSUE TITLE
content wont load after connection

### ISSUE THREAD

**Issue by trevor** [shaunxcode/datomicism#7]
after connecting to the datomic web server and finding a database, no content is loaded in the interface, yet URLs seem to work such as

```
http://localhost:6655/api/query?query=%5B%3Afind+%3Fe+%3Awhere+%5B%3Adb.part%2Fdb+%3Adb.install%2Fattribute+%3Fe%5D%5D
```

**Comment by shaunxcode** [comment]
Sorry about this, it is my fault for updating the underlying jsedn lib datomicism depends on and not having the package.json point to the earlier version. I am in the process now of updating it to work with the newer version now, should be working in a few hours.

**Comment by shaunxcode** [comment]
Could you verify that this is working for you now once you have 0.0.3 installed?

**Comment by shaunxcode** [comment]
This should now be resolved.
